//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corretaje.Payment.TransbankPayment {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.wswebpay.webpay.transbank.com/", ConfigurationName="TransbankPayment.WSWebpayService")]
    public interface WSWebpayService {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Corretaje.Payment.TransbankPayment.getTransactionResultResponse getTransactionResult(Corretaje.Payment.TransbankPayment.getTransactionResult request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Corretaje.Payment.TransbankPayment.getTransactionResultResponse> getTransactionResultAsync(Corretaje.Payment.TransbankPayment.getTransactionResult request);
        
        // CODEGEN: El parámetro 'tokenInput' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Corretaje.Payment.TransbankPayment.acknowledgeTransactionResponse acknowledgeTransaction(Corretaje.Payment.TransbankPayment.acknowledgeTransaction request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Corretaje.Payment.TransbankPayment.acknowledgeTransactionResponse> acknowledgeTransactionAsync(Corretaje.Payment.TransbankPayment.acknowledgeTransaction request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Corretaje.Payment.TransbankPayment.initTransactionResponse initTransaction(Corretaje.Payment.TransbankPayment.initTransaction request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Corretaje.Payment.TransbankPayment.initTransactionResponse> initTransactionAsync(Corretaje.Payment.TransbankPayment.initTransaction request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.wswebpay.webpay.transbank.com/")]
    public partial class transactionResultOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accountingDateField;
        
        private string buyOrderField;
        
        private cardDetail cardDetailField;
        
        private wsTransactionDetailOutput[] detailOutputField;
        
        private string sessionIdField;
        
        private System.DateTime transactionDateField;
        
        private bool transactionDateFieldSpecified;
        
        private string urlRedirectionField;
        
        private string vCIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string accountingDate {
            get {
                return this.accountingDateField;
            }
            set {
                this.accountingDateField = value;
                this.RaisePropertyChanged("accountingDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string buyOrder {
            get {
                return this.buyOrderField;
            }
            set {
                this.buyOrderField = value;
                this.RaisePropertyChanged("buyOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public cardDetail cardDetail {
            get {
                return this.cardDetailField;
            }
            set {
                this.cardDetailField = value;
                this.RaisePropertyChanged("cardDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("detailOutput", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public wsTransactionDetailOutput[] detailOutput {
            get {
                return this.detailOutputField;
            }
            set {
                this.detailOutputField = value;
                this.RaisePropertyChanged("detailOutput");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
                this.RaisePropertyChanged("sessionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime transactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
                this.RaisePropertyChanged("transactionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transactionDateSpecified {
            get {
                return this.transactionDateFieldSpecified;
            }
            set {
                this.transactionDateFieldSpecified = value;
                this.RaisePropertyChanged("transactionDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string urlRedirection {
            get {
                return this.urlRedirectionField;
            }
            set {
                this.urlRedirectionField = value;
                this.RaisePropertyChanged("urlRedirection");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string VCI {
            get {
                return this.vCIField;
            }
            set {
                this.vCIField = value;
                this.RaisePropertyChanged("VCI");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.wswebpay.webpay.transbank.com/")]
    public partial class cardDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cardNumberField;
        
        private string cardExpirationDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
                this.RaisePropertyChanged("cardNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cardExpirationDate {
            get {
                return this.cardExpirationDateField;
            }
            set {
                this.cardExpirationDateField = value;
                this.RaisePropertyChanged("cardExpirationDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.wswebpay.webpay.transbank.com/")]
    public partial class wsInitTransactionOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.wswebpay.webpay.transbank.com/")]
    public partial class wpmDetailInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serviceIdField;
        
        private string cardHolderIdField;
        
        private string cardHolderNameField;
        
        private string cardHolderLastName1Field;
        
        private string cardHolderLastName2Field;
        
        private string cardHolderMailField;
        
        private string cellPhoneNumberField;
        
        private System.DateTime expirationDateField;
        
        private string commerceMailField;
        
        private bool ufFlagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string serviceId {
            get {
                return this.serviceIdField;
            }
            set {
                this.serviceIdField = value;
                this.RaisePropertyChanged("serviceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cardHolderId {
            get {
                return this.cardHolderIdField;
            }
            set {
                this.cardHolderIdField = value;
                this.RaisePropertyChanged("cardHolderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cardHolderName {
            get {
                return this.cardHolderNameField;
            }
            set {
                this.cardHolderNameField = value;
                this.RaisePropertyChanged("cardHolderName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string cardHolderLastName1 {
            get {
                return this.cardHolderLastName1Field;
            }
            set {
                this.cardHolderLastName1Field = value;
                this.RaisePropertyChanged("cardHolderLastName1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string cardHolderLastName2 {
            get {
                return this.cardHolderLastName2Field;
            }
            set {
                this.cardHolderLastName2Field = value;
                this.RaisePropertyChanged("cardHolderLastName2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string cardHolderMail {
            get {
                return this.cardHolderMailField;
            }
            set {
                this.cardHolderMailField = value;
                this.RaisePropertyChanged("cardHolderMail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string cellPhoneNumber {
            get {
                return this.cellPhoneNumberField;
            }
            set {
                this.cellPhoneNumberField = value;
                this.RaisePropertyChanged("cellPhoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime expirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
                this.RaisePropertyChanged("expirationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string commerceMail {
            get {
                return this.commerceMailField;
            }
            set {
                this.commerceMailField = value;
                this.RaisePropertyChanged("commerceMail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public bool ufFlag {
            get {
                return this.ufFlagField;
            }
            set {
                this.ufFlagField = value;
                this.RaisePropertyChanged("ufFlag");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.wswebpay.webpay.transbank.com/")]
    public partial class wsInitTransactionInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private wsTransactionType wSTransactionTypeField;
        
        private string commerceIdField;
        
        private string buyOrderField;
        
        private string sessionIdField;
        
        private string returnURLField;
        
        private string finalURLField;
        
        private wsTransactionDetail[] transactionDetailsField;
        
        private wpmDetailInput wPMDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public wsTransactionType wSTransactionType {
            get {
                return this.wSTransactionTypeField;
            }
            set {
                this.wSTransactionTypeField = value;
                this.RaisePropertyChanged("wSTransactionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string commerceId {
            get {
                return this.commerceIdField;
            }
            set {
                this.commerceIdField = value;
                this.RaisePropertyChanged("commerceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string buyOrder {
            get {
                return this.buyOrderField;
            }
            set {
                this.buyOrderField = value;
                this.RaisePropertyChanged("buyOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
                this.RaisePropertyChanged("sessionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI", Order=4)]
        public string returnURL {
            get {
                return this.returnURLField;
            }
            set {
                this.returnURLField = value;
                this.RaisePropertyChanged("returnURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI", Order=5)]
        public string finalURL {
            get {
                return this.finalURLField;
            }
            set {
                this.finalURLField = value;
                this.RaisePropertyChanged("finalURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("transactionDetails", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public wsTransactionDetail[] transactionDetails {
            get {
                return this.transactionDetailsField;
            }
            set {
                this.transactionDetailsField = value;
                this.RaisePropertyChanged("transactionDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public wpmDetailInput wPMDetail {
            get {
                return this.wPMDetailField;
            }
            set {
                this.wPMDetailField = value;
                this.RaisePropertyChanged("wPMDetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.wswebpay.webpay.transbank.com/")]
    public enum wsTransactionType {
        
        /// <remarks/>
        TR_NORMAL_WS,
        
        /// <remarks/>
        TR_NORMAL_WS_WPM,
        
        /// <remarks/>
        TR_MALL_WS,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(wsTransactionDetailOutput))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.wswebpay.webpay.transbank.com/")]
    public partial class wsTransactionDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal sharesAmountField;
        
        private bool sharesAmountFieldSpecified;
        
        private int sharesNumberField;
        
        private bool sharesNumberFieldSpecified;
        
        private decimal amountField;
        
        private string commerceCodeField;
        
        private string buyOrderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal sharesAmount {
            get {
                return this.sharesAmountField;
            }
            set {
                this.sharesAmountField = value;
                this.RaisePropertyChanged("sharesAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sharesAmountSpecified {
            get {
                return this.sharesAmountFieldSpecified;
            }
            set {
                this.sharesAmountFieldSpecified = value;
                this.RaisePropertyChanged("sharesAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int sharesNumber {
            get {
                return this.sharesNumberField;
            }
            set {
                this.sharesNumberField = value;
                this.RaisePropertyChanged("sharesNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sharesNumberSpecified {
            get {
                return this.sharesNumberFieldSpecified;
            }
            set {
                this.sharesNumberFieldSpecified = value;
                this.RaisePropertyChanged("sharesNumberSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string commerceCode {
            get {
                return this.commerceCodeField;
            }
            set {
                this.commerceCodeField = value;
                this.RaisePropertyChanged("commerceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string buyOrder {
            get {
                return this.buyOrderField;
            }
            set {
                this.buyOrderField = value;
                this.RaisePropertyChanged("buyOrder");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.wswebpay.webpay.transbank.com/")]
    public partial class wsTransactionDetailOutput : wsTransactionDetail {
        
        private string authorizationCodeField;
        
        private string paymentTypeCodeField;
        
        private int responseCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string authorizationCode {
            get {
                return this.authorizationCodeField;
            }
            set {
                this.authorizationCodeField = value;
                this.RaisePropertyChanged("authorizationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string paymentTypeCode {
            get {
                return this.paymentTypeCodeField;
            }
            set {
                this.paymentTypeCodeField = value;
                this.RaisePropertyChanged("paymentTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("responseCode");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTransactionResult", WrapperNamespace="http://service.wswebpay.webpay.transbank.com/", IsWrapped=true)]
    public partial class getTransactionResult {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.wswebpay.webpay.transbank.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tokenInput;
        
        public getTransactionResult() {
        }
        
        public getTransactionResult(string tokenInput) {
            this.tokenInput = tokenInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTransactionResultResponse", WrapperNamespace="http://service.wswebpay.webpay.transbank.com/", IsWrapped=true)]
    public partial class getTransactionResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.wswebpay.webpay.transbank.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Corretaje.Payment.TransbankPayment.transactionResultOutput @return;
        
        public getTransactionResultResponse() {
        }
        
        public getTransactionResultResponse(Corretaje.Payment.TransbankPayment.transactionResultOutput @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="acknowledgeTransaction", WrapperNamespace="http://service.wswebpay.webpay.transbank.com/", IsWrapped=true)]
    public partial class acknowledgeTransaction {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.wswebpay.webpay.transbank.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tokenInput;
        
        public acknowledgeTransaction() {
        }
        
        public acknowledgeTransaction(string tokenInput) {
            this.tokenInput = tokenInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="acknowledgeTransactionResponse", WrapperNamespace="http://service.wswebpay.webpay.transbank.com/", IsWrapped=true)]
    public partial class acknowledgeTransactionResponse {
        
        public acknowledgeTransactionResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="initTransaction", WrapperNamespace="http://service.wswebpay.webpay.transbank.com/", IsWrapped=true)]
    public partial class initTransaction {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.wswebpay.webpay.transbank.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Corretaje.Payment.TransbankPayment.wsInitTransactionInput wsInitTransactionInput;
        
        public initTransaction() {
        }
        
        public initTransaction(Corretaje.Payment.TransbankPayment.wsInitTransactionInput wsInitTransactionInput) {
            this.wsInitTransactionInput = wsInitTransactionInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="initTransactionResponse", WrapperNamespace="http://service.wswebpay.webpay.transbank.com/", IsWrapped=true)]
    public partial class initTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.wswebpay.webpay.transbank.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Corretaje.Payment.TransbankPayment.wsInitTransactionOutput @return;
        
        public initTransactionResponse() {
        }
        
        public initTransactionResponse(Corretaje.Payment.TransbankPayment.wsInitTransactionOutput @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSWebpayServiceChannel : Corretaje.Payment.TransbankPayment.WSWebpayService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSWebpayServiceClient : System.ServiceModel.ClientBase<Corretaje.Payment.TransbankPayment.WSWebpayService>, Corretaje.Payment.TransbankPayment.WSWebpayService {
        
        public WSWebpayServiceClient() {
        }
        
        public WSWebpayServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSWebpayServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSWebpayServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSWebpayServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Corretaje.Payment.TransbankPayment.getTransactionResultResponse Corretaje.Payment.TransbankPayment.WSWebpayService.getTransactionResult(Corretaje.Payment.TransbankPayment.getTransactionResult request) {
            return base.Channel.getTransactionResult(request);
        }
        
        public Corretaje.Payment.TransbankPayment.transactionResultOutput getTransactionResult(string tokenInput) {
            Corretaje.Payment.TransbankPayment.getTransactionResult inValue = new Corretaje.Payment.TransbankPayment.getTransactionResult();
            inValue.tokenInput = tokenInput;
            Corretaje.Payment.TransbankPayment.getTransactionResultResponse retVal = ((Corretaje.Payment.TransbankPayment.WSWebpayService)(this)).getTransactionResult(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Corretaje.Payment.TransbankPayment.getTransactionResultResponse> Corretaje.Payment.TransbankPayment.WSWebpayService.getTransactionResultAsync(Corretaje.Payment.TransbankPayment.getTransactionResult request) {
            return base.Channel.getTransactionResultAsync(request);
        }
        
        public System.Threading.Tasks.Task<Corretaje.Payment.TransbankPayment.getTransactionResultResponse> getTransactionResultAsync(string tokenInput) {
            Corretaje.Payment.TransbankPayment.getTransactionResult inValue = new Corretaje.Payment.TransbankPayment.getTransactionResult();
            inValue.tokenInput = tokenInput;
            return ((Corretaje.Payment.TransbankPayment.WSWebpayService)(this)).getTransactionResultAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Corretaje.Payment.TransbankPayment.acknowledgeTransactionResponse Corretaje.Payment.TransbankPayment.WSWebpayService.acknowledgeTransaction(Corretaje.Payment.TransbankPayment.acknowledgeTransaction request) {
            return base.Channel.acknowledgeTransaction(request);
        }
        
        public void acknowledgeTransaction(string tokenInput) {
            Corretaje.Payment.TransbankPayment.acknowledgeTransaction inValue = new Corretaje.Payment.TransbankPayment.acknowledgeTransaction();
            inValue.tokenInput = tokenInput;
            Corretaje.Payment.TransbankPayment.acknowledgeTransactionResponse retVal = ((Corretaje.Payment.TransbankPayment.WSWebpayService)(this)).acknowledgeTransaction(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Corretaje.Payment.TransbankPayment.acknowledgeTransactionResponse> Corretaje.Payment.TransbankPayment.WSWebpayService.acknowledgeTransactionAsync(Corretaje.Payment.TransbankPayment.acknowledgeTransaction request) {
            return base.Channel.acknowledgeTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Corretaje.Payment.TransbankPayment.acknowledgeTransactionResponse> acknowledgeTransactionAsync(string tokenInput) {
            Corretaje.Payment.TransbankPayment.acknowledgeTransaction inValue = new Corretaje.Payment.TransbankPayment.acknowledgeTransaction();
            inValue.tokenInput = tokenInput;
            return ((Corretaje.Payment.TransbankPayment.WSWebpayService)(this)).acknowledgeTransactionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Corretaje.Payment.TransbankPayment.initTransactionResponse Corretaje.Payment.TransbankPayment.WSWebpayService.initTransaction(Corretaje.Payment.TransbankPayment.initTransaction request) {
            return base.Channel.initTransaction(request);
        }
        
        public Corretaje.Payment.TransbankPayment.wsInitTransactionOutput initTransaction(Corretaje.Payment.TransbankPayment.wsInitTransactionInput wsInitTransactionInput) {
            Corretaje.Payment.TransbankPayment.initTransaction inValue = new Corretaje.Payment.TransbankPayment.initTransaction();
            inValue.wsInitTransactionInput = wsInitTransactionInput;
            Corretaje.Payment.TransbankPayment.initTransactionResponse retVal = ((Corretaje.Payment.TransbankPayment.WSWebpayService)(this)).initTransaction(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Corretaje.Payment.TransbankPayment.initTransactionResponse> Corretaje.Payment.TransbankPayment.WSWebpayService.initTransactionAsync(Corretaje.Payment.TransbankPayment.initTransaction request) {
            return base.Channel.initTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Corretaje.Payment.TransbankPayment.initTransactionResponse> initTransactionAsync(Corretaje.Payment.TransbankPayment.wsInitTransactionInput wsInitTransactionInput) {
            Corretaje.Payment.TransbankPayment.initTransaction inValue = new Corretaje.Payment.TransbankPayment.initTransaction();
            inValue.wsInitTransactionInput = wsInitTransactionInput;
            return ((Corretaje.Payment.TransbankPayment.WSWebpayService)(this)).initTransactionAsync(inValue);
        }
    }
}
