export const BARRIOS_COMUNAS = {
  "La Reina": [
    "Blest Gana",
    "Metro Príncipe de Gales - Country Club",
    "Metro Simón BolivarMetro Simón Bolivar",
    "La Reina Alta",
    "Francisco de Villagra",
    "Carlos Ossandón",
    "Troncos Viejos",
    "Palmas de Mallorca",
    "Pepe Vila",
    "Villa La Reina",
  ],
  "San Miguel": [
    "Ciudad del Niño", 
    "Lo Vial", 
    "El Llano"
  ],
  "Estación Central": [
    "Metro Ecuador",
    "Nogales - San Eugenio",
    "San Alberto Hurtado",
    "Villa Francia",
    "Metro Pajaritos",
    "Metro Las Rejas",
    "Universidad de Santiago",
  ],
  "Peñalolen": [
    "Quilín - Cousiño Macul",
    "Arboretum - Club de Campo",
    "Ictinos",
    "Las Pircas",
    "Las Torres",
    "Metro Los Presidentes - Lo Hermida",
    "Metro Los Orientales",
    "Las Parcelas",
    "Villa San Carlos",
    "Casa Grande",
    "Quebrada de Macul",
    "Esperanza Andina",
    "Comunidad Ecológica",
  ],
  "La Florida": [
    "Plaza Vespucio",
    "La Florida Alto",
    "Vicente Valdés",
    "Metro Mirador",
    "La Florida",
    "San José de La Estrella",
    "Los Quillayes",
    "Trinidad",
    "Lo Cañas - Alto Macul",
    "Rojas Magallanes",
    "Nuevo Amanecer - Chacón Zamora",
    "Metro Santa Julia",
    "Jardines de La Viña",
  ],
  "Ñuñoa": [
    "Plaza Ñuñoa",
    "Metro Ñuñoa",
    "Metro Monseñor Eyzaguirre",
    "Plaza Egaña",
    "Metro Irarrázaval",
    "Estadio Nacional",
    "Diagonal Oriente",
    "Parque Juan XXIII",
    "Parque San Eugenio - Metro Ñuble",
    "Diego de Almagro",
    "Juan Gómez Millas",
    "Villa Frei",
    "Parque Botánico",
    "Amapolas",
    "Villa Los Jardínes - Villa Los Presidentes",
    "Metro Simón Bolivar",
  ],
  "Las Condes": [
    "Barrio El Golf",
    "Sebastián Elcano",
    "Metro Manquehue - Apumanque",
    "Rotonda Atenas",
    "Parque Arauco",
    "Metro Escuela Militar",
    "Alto Las Condes",
    "San Carlos de Apoquindo",
    "Vaticano",
    "Metro Hernando de Magallanes",
    "Centro Financiero",
    "Colón Oriente - Vital Apoquindo",
    "El Remanso",
    "Estoril",
    "Los Dominicos",
    "Mall Sport",
    "Nueva Las Condes",
    "Parque Padre Alberto Hurtado",
    "Quinchamalí",
    "San Damián",
  ],
  "Lo Barnechea": [
    "La Dehesa",
    "Centros Invernales",
    "Puente Nuevo",
    "Los Trapenses",
    "El Huinganal",
    "Valle Escondido",
    "Antigua Lo Barnechea",
    "El Arrayán",
    "Cerro Dieciocho",
    "Camino a Farellones",
    "Valle Nevado",
    "Manquehue Oriente",
    "Jardín La Dehesa",
    "Plaza San Enrique",
  ],
  "Vitacura": [
    "Parque Bicentenario",
    "Pío XI",
    "Tabancura",
    "Santa María de Manquehue",
    "Lo Curro",
    "Santa Teresa de Los Andes",
    "Jardín Del Este",
    "Estadio Croata",
    "Estadio Manquehue",
    "La Llavería",
    "Borde Río - Casa Piedra",
    "Juan XXIII",
    "Luis Pasteur",
    "Villa El Dorado",
    "Nuestra Señora del Rosario",
  ],
  "Macul": [
    "Las Dalias",
    "Metro Camino Agrícola",
    "Metro Las Torres",
    "Villa Macul",
    "Escuela Agrícola",
    "Pedrero - Estadio Monumental",
    "Santa Julia de Macul",
    "Metro Carlos Valdovinos",
    "Metro Quilín",
    "Metro Los Presidentes",
    "Metro Macul",
    "Metro Rodrigo de Araya",
    "Campus San Joaquín",
    "Lomas de Macul",
  ],
  "Colina": [
    "Chicureo", 
    "Centro de Colina", 
    "Casas de Chacabuco", 
    "Colina"
  ],
  "Santiago": [
    "Centro Histórico de Santiago",
    "Santa Isabel",
    "Bulnes",
    "Parque O'Higgins",
    "San Diego",
    "Barrio Yungay",
    "Bogotá - Sierra Bella",
    "Barrio Diez de Julio",
    "Barrio Brasil",
    "Barrio Lastarria",
    "Barrio República",
    "Barrio San Borja",
    "Club Hípico",
    "Ejército - Toesca",
    "Franklin - Biobío",
    "Parque Los Reyes",
    "Parque Almagro",
    "Dieciocho",
    "Meiggs",
  ],
  "Providencia": [
    "Las Lilas",
    "Los Leones",
    "Pedro de Valdivia",
    "Manuel Montt",
    "Inés de Suárez",
    "Campus Oriente",
    "Barrio Italia",
    "Metro Tobalaba - Mall Costanera",
    "Metro Bilbao",
    "Bellavista",
    "Pedro de Valdivia Norte",
    "Plaza Italia",
    "Salvador",
  ],
  "La Reina": [
    "Blest Gana",
    "Metro Príncipe de Gales - Country Club",
    "Metro Simón Bolivar",
    "La Reina Alta",
    "Francisco de Villagra",
    "Carlos Ossandón",
    "Troncos Viejos",
    "Palmas de Mallorca",
    "Pepe Vila",
    "Villa La Reina"
  ],
  "Huechuraba": [
    "Pedro Fontova", 
    "Ciudad Empresarial", 
    "Bosques de la Pirámide",
    "La Pincoya - El Barrero",
    "El Rosal",
    "Los Libertadores"
  ],
  "Independencia": [
    "Hospitales", 
    "Plaza Chacabuco", 
    "Mirador Viejo", 
    "Juan Antonio Ríos",
    "Metro Cal y Canto"
  ],
 "La Cisterna": [
   "Lo Ovalle", 
   "El Parrón", 
   "Metro La Cisterna"
  ]
};

export const MESES = [
  "Enero",
  "Febrero",
  "Marzo",
  "Abril",
  "Mayo",
  "Junio",
  "Julio",
  "Agosto",
  "Septiembre",
  "Octubre",
  "Noviembre",
  "Diciembre",
];

export const BANCOS = [
  "Banco Santander",
  "Scotiabank Azul",
  "Banco BICE",
  "Banco Internacional",
  "Banco Itaú",
  "Banco de Chile / Edwards-Citi",
  "Corpbanca",
  "Banco Crédito e Inversiones",
  "Banco Estado", 
  "Banco Falabella", 
  "Banco Security", 
  "Scotiabank",
  "Rabobank",
  "HSBC Bank", 
  "Banco Ripley", 
  "Banco Paris", 
  "Banco Consorcio", 
  "Coopeuch", 
  "Prepago Los Heroes",
  "Tenpo Prepago S.A"
]

export const TIPOS_CUENTA_BANCARIA = [
  "Cuenta Corriente", 
  "Cuenta Vista", 
  "Chequera Electrónica", 
  "Cuenta de Ahorro", 
];

export const DIAS_SEMANA_CORTOS = ["Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sa"];

export const STANDARD_ERROR_MESSAGES = {
  401: "Debe estar logeado para realizar esta acción",
  403: "No posee el tipo de cuenta con los permisos necesarios para realizar esta acción",
  415: "No se permite el formato de archivo subido",
  500: "Error interno del servidor",
  501: "Acción no disponible por el momento",
  503: "Servicio no disponible"
}