using System.Collections.Generic;
using System.Linq;
using Corretaje.Domain;
using Corretaje.Repository;
using MongoDB.Bson;

namespace Corretaje.Api.Seed
{
    public class Seeds
    {
        public static void Initialize(IRepository<Configuracion> configuracion)
        {
            if (configuracion.GetAll().Result.Any()) return;

            var listComunas = new List<string>
            {
                "Aisén",
                "Algarrobo",
                "Alhué",
                "Alto del Carmen",
                "ANCUD",
                "Andacollo",
                "Angol",
                "Antártica",
                "Antofagasta",
                "Antuco",
                "Arauco",
                "Arica",
                "BUIN",
                "Bulnes",
                "Cabildo",
                "Cabrero",
                "Calama",
                "Calbuco",
                "Caldera",
                "Calera",
                "Calera de Tango",
                "Calle Larga",
                "Camarones",
                "Camiña",
                "CANELA",
                "CAÑETE",
                "Carahue",
                "Cartagena",
                "Casablanca",
                "Castro",
                "Catemu",
                "Cauquenes",
                "Cerrillos",
                "Cerro Navia",
                "Chaitén",
                "Chañaral",
                "Chanco",
                "Chépica",
                "Chiguayante",
                "Chile Chico",
                "Chillán",
                "Chillán Viejo",
                "Chimbarongo",
                "Chonchi",
                "Cisnes",
                "Cobquecura",
                "Cochamo",
                "Cochrane",
                "Codegua",
                "Coelemu",
                "Coihaique",
                "Coihueco",
                "Coinco",
                "Colbún",
                "Colchane",
                "COLINA",
                "Collipulli",
                "Coltauco",
                "Combarbalá",
                "Concepción",
                "Conchalí",
                "Concón",
                "Constitución",
                "Contulmo",
                "Copiapó",
                "COQUIMBO",
                "Coronel",
                "Corral",
                "Cunco",
                "Curacautín",
                "Curacavi",
                "Curacaví",
                "Curaco de Velez",
                "Curanilahue",
                "Curarrehue",
                "Curepto",
                "Curicó",
                "Dalcahue",
                "Diego de Almagro",
                "Doñihue",
                "El Belloto",
                "El Bosque",
                "El Carmen",
                "El Monte",
                "El Quisco",
                "El Tabo",
                "Empedrado",
                "Ercilla",
                "Estación Central",
                "Florida",
                "Freire",
                "Freirina",
                "Fresia",
                "Frutillar",
                "Futalefu",
                "Futrono",
                "Galvarino",
                "General Lagos",
                "Gorbea",
                "Graneros",
                "Guaitecas",
                "Hijuelas",
                "Horcón",
                "Hualaihue",
                "Hualañe",
                "Hualqui",
                "Huara",
                "Huasco",
                "HUECHURABA",
                "Illapel",
                "Independencia",
                "Iquique",
                "Isla de maipo",
                "Isla de Pascua",
                "Isla Negra",
                "Juan Fernández",
                "La Calera",
                "La Cisterna",
                "La Cruz",
                "La Estrella",
                "La Florida",
                "La Granja",
                "La Higuera",
                "La Ligua",
                "La Pintana",
                "LA REINA",
                "La Serena",
                "La Unión",
                "Lago Ranco",
                "Lago Verde",
                "Laguna Blanca",
                "Laja",
                "LAMPA",
                "Lanco",
                "Las Cabras",
                "LAS CONDES",
                "Lautaro",
                "Lebu",
                "Licantén",
                "Limache",
                "Linares",
                "Litueche",
                "Llaillay",
                "Llanquihue",
                "LO BARNECHEA",
                "Lo Espejo",
                "Lo Prado",
                "Lolol",
                "Loncoche",
                "Longaví",
                "Lonquimay",
                "Los Alamos",
                "LOS ANDES",
                "Los Angeles",
                "Los Lagos",
                "Los Muermos",
                "Los Sauces",
                "Los Vilos",
                "Lota",
                "Lumaco",
                "Machalí",
                "Macul",
                "Mafil",
                "Maipú",
                "Maitencillo",
                "Malloa",
                "Marchigüe",
                "María Elena",
                "María Pinto",
                "Mariquina",
                "Maule",
                "Maullín",
                "Mejillones",
                "Melipeuco",
                "Melipilla",
                "Molina",
                "Monte Patria",
                "Mostazal",
                "Mulchén",
                "Nacimiento",
                "Nancagua",
                "Natales",
                "Navarino",
                "Navidad",
                "Negrete",
                "Ninhue",
                "Ñiquén",
                "Nogales",
                "Nueva Imperial",
                "ÑUÑOA",
                "O'higgins",
                "Olivar",
                "Ollagüe",
                "Olmué",
                "Osorno",
                "Ovalle",
                "Padre Hurtado",
                "Padre las Casas",
                "Paiguano",
                "Paillaco",
                "PAINE",
                "Palena",
                "Palmilla",
                "Panguipulli",
                "Panquehue",
                "PAPUDO",
                "Paredones",
                "Parral",
                "Pedro Aguirre Cerda",
                "Pelarco",
                "Pelluhue",
                "Pemuco",
                "Peñablanca",
                "Peñaflor",
                "peñalolen",
                "peñalolén",
                "Pencahue",
                "Penco",
                "Peralillo",
                "Perquenco",
                "Petorca",
                "Peumo",
                "Pica",
                "Pichidegua",
                "Pichilemu",
                "Pinto",
                "Pirque",
                "Pitrufquén",
                "Placilla",
                "Placilla de Peñuelas",
                "Portezuelo",
                "Porvenir",
                "Pozo Almonte",
                "Primavera",
                "PROVIDENCIA",
                "Puchuncavi",
                "Puchuncaví",
                "Pucón",
                "Pudahuel",
                "Puente Alto",
                "Puerto Montt",
                "Puerto Octay",
                "Puerto Varas",
                "Pumanque",
                "Punitaqui",
                "Punta Arenas",
                "Puqueldón",
                "Purén",
                "Purranque",
                "Putaendo",
                "Putre",
                "Puyehue",
                "Queilén",
                "Quellón",
                "Quemchi",
                "Quilaco",
                "Quilicura",
                "Quilleco",
                "Quillón",
                "Quillota",
                "Quilpué",
                "Quinchao",
                "Quinta de Tilcoco",
                "Quinta Normal",
                "Quintero",
                "Quirihue",
                "Rancagua",
                "Ranquil",
                "Rapel de Navidad",
                "Rauco",
                "Recoleta",
                "Reñaca",
                "Renaico",
                "Renca",
                "Rengo",
                "Requínoa",
                "Retiro",
                "Rinconada",
                "Río Bueno",
                "Río Claro",
                "Río Hurtado",
                "Río Ibáñez",
                "Río Negro",
                "Río Verde",
                "Romeral",
                "Saavedra",
                "Sagrada Familia",
                "Salamanca",
                "San Antonio",
                "SAN BERNARDO",
                "San Carlos",
                "San Clemente",
                "San Esteban",
                "San Fabián",
                "San Felipe",
                "San Fernando",
                "San Francisco de Las Condes",
                "San Gregorio",
                "San Ignacio",
                "San Javier",
                "San Joaquín",
                "San José de Maipo",
                "San Juan de la Costa",
                "San Miguel",
                "San Nicolás",
                "San Pablo",
                "San Pedro",
                "San Pedro de Atacama",
                "San Pedro de la Paz",
                "San Ramón",
                "San Rosendo",
                "San Vicente",
                "Santa Bárbara",
                "Santa Cruz",
                "Santa Juana",
                "Santa María",
                "Santiago",
                "Santo Domingo",
                "Sierra Gorda",
                "TALAGANTE",
                "Talca",
                "Talcahuano",
                "TalTal",
                "Temuco",
                "Teno",
                "Teodoro Schmidt",
                "Tierra Amarilla",
                "Til Til",
                "Timaukel",
                "Tirúa",
                "Tocopilla",
                "Toltén",
                "Tomé",
                "Torres del Paine",
                "Tortel",
                "Traiguén",
                "Treguaco",
                "Tucapel",
                "Valdivia",
                "Vallenar",
                "Valparaíso",
                "Vichuquén",
                "Victoria",
                "Vicuña",
                "Vilcún",
                "Villa Alegre",
                "Villa Alemana",
                "Villarrica",
                "Viña del Mar",
                "VITACURA",
                "Yerbas Buenas",
                "Yumbel",
                "Yungay",
                "Zapallar"
            };

            var configComunas =
                new Configuracion
                {
                    Key = "PortalInmobiliarioComunas",
                    Value = listComunas.ToJson()
                };

            configuracion.Insert(configComunas);
        }
    }
}